### ISSUE TITLE
Create New File and Fork This Repository combined into one step

### ISSUE THREAD

**Issue by danzera** [approachable-io/getting-started#28]
When clicking `Create New File` in another person's repo, it looks like GitHub has eliminated the `Fork this repository and propose changes` step. It now automatically creates your forked repo and goes directly to creating a new file (pictured below).

You could either adjust the walkthrough slightly to account for this and change the image accordingly, or things could be changed a bit to step through 'manually' forking the repo using the "Fork" button in the top right.

![screen shot 2017-11-29 at 10 32 19 am](https://user-images.githubusercontent.com/24783478/33388322-457b20b6-d4f5-11e7-96a1-03567cbd297a.png)

**Comment by LukeSchlangen** [comment]
This looks great! I'd love to have a PR for this.

**Comment by danzera** [comment]
Do you think it makes more sense to walk through the forking process or just describe what's going on when `Create New File` is clicked?

I assume it's more likely that people fork projects and pull them down locally to work on issues as opposed to creating a file directly on GitHub, so it might make sense to walk through the forking process. However, that could be a separate topic since this doesn't really get into the whole local repo vs. GitHub repo business.

**Comment by LukeSchlangen** [comment]
For this project in particular, most people don't clone it down to work on it locally (because it's an introduction for people who may be unfamiliar with the Pull Request process and are sometimes unfamiliar with git). It seems like a balance, do we make it easier, or do we try to explain what's going on under the hood. Maybe having user's click the `Fork` button is a good way to explain what's going on under the hood. Thanks for pointing that out @danzera.

Let's close it for now and if this issue receives more interest in the future (to reduce complexity), we'll open it back up.
